apiVersion: v1
kind: Pod
metadata:
  name: mypod
  labels:
    run: mypod
spec:
  containers:
    - name: web3
      image: navinraaj/sit737_2023_t1_prac7c:latest
      imagePullPolicy: Never
      ports:
        - containerPort: 8080
  dnsPolicy: ClusterFirst
  restartPolicy: Always
