version: '3.4'

services:
  web1:
    image: sit7372023t1prac7c
    container_name: web3
    ports:
      - 49163:8080
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: on-failure